name: Update store

on: 
  push:
    branches:
      - main
jobs:
  update:
    name: |
      Update the jbrowse.org plugin store with
      the new list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Copy JSON file to S3
        run: |
          aws s3 cp plugins.json s3://jbrowse.org/plugin-store/plugins.json
          aws cloudfront create-invalidation --distribution-id E13LGELJOT4GQO --paths "/plugin-store/*"
